version: '3.8'

services:
  backend:
    build:
      context: ./ntc-fleet-backend
      dockerfile: Dockerfile
    container_name: ntc_fleet_backend
    ports:
      - "5000:5000"
    env_file:
      - ./ntc-fleet-backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./ntc-fleet-frontend
      dockerfile: Dockerfile
    container_name: ntc_fleet_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
